// Generated by https://quicktype.io

export interface Chss {
    id: string;
    category: string;
    description: string;
    name: string;
    address: string;
    phone: string;
    lat: number;
    long: number;
}

export interface AfterViewInit {
    ngAfterViewInit(): void;
}
